version: 2.1

jobs:
  backend_build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: npm install -g yarn
      - run:
          name: Build Backend
          command: cd reactnd-contacts-server && npm run build

workflows:
  version: 2
  build:
    jobs:
      - backend_build